### ISSUE TITLE
vulkan support?

### ISSUE THREAD

**Issue by nergdron** [go-gl/glow#76] opened 2016-05-13 07:35 UTC
Just wondering if you've considered adding Vulkan API binding generation support? I know it's not precisely OpenGL, but the binding generation should work almost the same way given the source for the APIs is the same, and having Go support for this new high performance API would be really useful for GPU computing purposes.

**Comment by shurcooL** [comment] 2016-05-13 07:56
This issue is a duplicate of another, so I'll close this and point you there.

Please see https://github.com/go-gl/gl/issues/30.

Also see https://github.com/go-khronos, it's an organization created by one of go-gl maintainers and he's working on a generator for Vulkan bindings (and the bindings themselves, that are generated). /cc @hydroflame

**Closed by shurcooL** 2016-05-13 07:56 UTC

**Comment by hydroflame** [comment] 2016-05-13 08:09
@nergdron To be honest we have no proof vulkan in Go will be any faster then OpenGL, it depends on how efficient you are in optimising your application and more importantly, how many calls to vulkan you'll have to make (cgo calls are expensive)

**Comment by 4ydx** [comment] 2016-05-30 15:13
Whether or not it is faster, I am under the impression that it will ultimately be easier to debug applications written in Vulkan.  Or not?  Dealing with OpenGL in my current pet project makes me feel like I am going back 10 years in time to a lack of proper javascript debugging support in IE.  I am probably just not seasoned enough to really make a judgement, but as a newbie OpenGL programmer on linux, let's just say the experience hasn't been very pleasant so far :)  Anyway, I am eager to see how your work progresses @hydroflame .

**Comment by snuk182** [comment] 2016-06-24 11:22
@4ydx if you found yourself unsatisfied with OpenGL just because of its "unpleasant" API, then I'm pretty sure you'll be utterly disappointed with Vulkan, because it is even more low-level. Simple hello world triangle requires nearly 1000 lines of code, comparing to ~50 for GL. There is some sense that we don't have VK API port for Go in a form of stupid bindings, just because Go is too high-level for it, and everything will end with the same performance as GL with a cost of 5-10 times more code.

**Comment by 4ydx** [comment] 2016-07-01 03:05
@snuk182 If you reread my comment, you will see that I am complaining about ease of debugging issues within opengl.  I have gotten better since then, but I still feel like I am dealing with a black box.  Perhaps Vulkan wont alleviate this issue, but I was under the impression that the debugging tools available would be vastly better than what is available for opengl.  I am aware of the increased code base required for getting a vulkan application up and running :)  Hopefully somebody dives in and figures this out, but it isn't looking hopeful.
