### ISSUE TITLE
error generating package

### ISSUE THREAD

**Issue by ben-clayton** [go-gl/glow#60] opened 2015-04-01 15:11 UTC
I just had a try at building GLES2 bindings using GLOW on Windows:
```bash
> %GOPATH%/bin/glow generate -api="gles2" -version="2.0"
2015/04/01 16:06:54 error generating package:exit status 1
```

It does however, look like it built all the files:
```bash
> ls gl
conversions.go  debug.go  package.go  procaddr.go
```

I get the same error trying to build GL. I guess I'll find out soon enough if the content of those files is broken.

**Comment by shurcooL** [comment] 2015-04-01 15:23
First thing I'd check is that the path to the xml files is right. You're not specifying it in the parameters, so I think your cwd should be glow's package folder.

In any case, that error isn't very descriptive and should be fixed. Looking into it.

**Comment by shurcooL** [comment] 2015-04-01 15:25
@ben-clayton, did you follow the steps at https://github.com/go-gl/glow#custom-packages?

**Comment by shurcooL** [comment] 2015-04-01 15:28
Never mind, I can reproduce this on OS X too even with the package root as the cwd. The generated files look okay, so it might be something non-fatal.

**Comment by shurcooL** [comment] 2015-04-01 15:32
Yeah, the problem isn't fatal, and it's a bug in code I've written.

It happens here:

```Go
// gofmt the generated .go files.
if err := exec.Command("go", "fmt", dir).Run(); err != nil {
	return err
}
```

I've only tested it with specifying a relative path for the output folder. But the default value is simply "gl", so the command run is `go fmt gl` and fails because gl is not a valid package. It should be doing `go fmt ./gl` instead.

**Closed** 2015-04-01 18:44 UTC
