### ISSUE TITLE
More idiomatic bindings

### ISSUE THREAD

**Issue by tux21b** [go-gl/glow#53] opened 2015-02-23 13:03 UTC
I've read the announcement and was eager to test the new bindings. Unfortunately I am not that happy with the new API. For example, take a look at:

```
// Replaces the source code in a shader object
func ShaderSource(shader uint32, count int32, xstring **uint8, length *int32)
```

I do not mind if ShaderSource is a method (like before) or a function, but working with this signature within Go is extremely cumbersome and error-prone and I had to look up the C documentation to understand the parameters. Something like `ShaderSource(shader uint32, sources []string)` or `type Shader uint32; func (s Shader) Source(sources []string)` would be definitely better.

Are there plans to improve the generated bindings? It might be necessary to add additional annotations to guide the automatic generation.

**Comment by errcw** [comment] 2015-02-23 17:19
The bindings are intended to mirror the OpenGL API as closely as possible. With these low-level building blocks it is possible to build a Go-idiomatic interface to OpenGL but that is not the intent of `Glow`.

**Comment by shurcooL** [comment] 2015-03-18 04:32
As en example of experimental, slightly higher-level bindings on top of these low-level bindings, feel free to take a look at:

https://godoc.org/github.com/shurcooL/gogl#Context.GetProgramInfoLog

**Comment by shurcooL** [comment] 2015-04-01 16:03
Another higher level, more idiomatic Go bindings for GL with multiple backends (OpenGL on desktop, OpenGL ES on mobile, more coming soon):

https://godoc.org/golang.org/x/mobile/gl

Perhaps that is closer to what you're looking for, @tux21b?

**Comment by errcw** [comment] 2017-05-09 03:10
Closing this because glow by design mirrors the OpenGL API, as ugly as that may be in Go.

**Closed by errcw** 2017-05-09 03:10 UTC
